version: 2
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          key: gradle-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

  test:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: ./gradlew jvmTest
      - run: ./gradlew linuxX64Test

workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
